apiVersion: v2
name: cache-seeder
description: A Helm chart for cache-seeder service
type: application
version: 2.1.1
appVersion: 2.1.1

dependencies:
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
    
